name: Rust

on: [push, pull_request]

env:
  MSRV: 1.62.1

jobs:
  build_lib_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - nightly
          - beta
          - stable
          - $MSRV
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Obtain Rust
      run: rustup override set ${{ matrix.rust }}
    - name: Build library
      run: cargo build --verbose --lib
    - name: Build examples
      run: cargo build --verbose --lib --examples
    - name: Run unit tests
      run: cargo test --verbose
    - name: "Run README sample (TODO: update me)"
      run: cargo run --example sample
  build_bin_spec:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - nightly
          - beta
          - stable
          - $MSRV
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Obtain Rust
      run: rustup override set ${{ matrix.rust }}
    - name: Build binary
      run: cargo build --verbose --bin comrak --release
    - name: Run spec tests
      run: script/cibuild
  build_wasm:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - nightly
          - beta
          - stable
          - $MSRV
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Obtain Rust
      run: rustup override set ${{ matrix.rust }}
    - name: Setup for wasm
      run: rustup target add wasm32-unknown-unknown
    - name: Build
      run: cargo build --verbose --target wasm32-unknown-unknown
    - name: Build examples
      run: cargo build --verbose --target wasm32-unknown-unknown --examples
  no_features_build_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - nightly
          - beta
          - stable
          - $MSRV
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Obtain Rust
      run: rustup override set ${{ matrix.rust }}
    - name: Build and test with no features
      run: cargo test --no-default-features --tests
  lockfile:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Obtain Rust
      run: rustup override set $MSRV
    - name: Build and test with no features
      run: cargo +stable build --locked --release --all-features
  clippy_format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Obtain Rust
      run: rustup override set $MSRV
    - name: Check clippy
      run: rustup component add clippy && cargo clippy
    - name: Check formatting
      run: rustup component add rustfmt && cargo fmt -- --check
